// Code generated by protoc-gen-go. DO NOT EDIT.
// source: manifest.proto

package internal

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ManifestV1 struct {
	Size                 uint64              `protobuf:"varint,1,opt,name=Size,proto3" json:"Size,omitempty"`
	Slices               []*ManifestV1_Slice `protobuf:"bytes,2,rep,name=Slices,proto3" json:"Slices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ManifestV1) Reset()         { *m = ManifestV1{} }
func (m *ManifestV1) String() string { return proto.CompactTextString(m) }
func (*ManifestV1) ProtoMessage()    {}
func (*ManifestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_0bb23f43f7afb4c1, []int{0}
}

func (m *ManifestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManifestV1.Unmarshal(m, b)
}
func (m *ManifestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManifestV1.Marshal(b, m, deterministic)
}
func (m *ManifestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManifestV1.Merge(m, src)
}
func (m *ManifestV1) XXX_Size() int {
	return xxx_messageInfo_ManifestV1.Size(m)
}
func (m *ManifestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_ManifestV1.DiscardUnknown(m)
}

var xxx_messageInfo_ManifestV1 proto.InternalMessageInfo

func (m *ManifestV1) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ManifestV1) GetSlices() []*ManifestV1_Slice {
	if m != nil {
		return m.Slices
	}
	return nil
}

type ManifestV1_Slice struct {
	Checksum             []byte   `protobuf:"bytes,1,opt,name=Checksum,proto3" json:"Checksum,omitempty"`
	Offset               uint64   `protobuf:"varint,2,opt,name=Offset,proto3" json:"Offset,omitempty"`
	Length               uint64   `protobuf:"varint,3,opt,name=Length,proto3" json:"Length,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ManifestV1_Slice) Reset()         { *m = ManifestV1_Slice{} }
func (m *ManifestV1_Slice) String() string { return proto.CompactTextString(m) }
func (*ManifestV1_Slice) ProtoMessage()    {}
func (*ManifestV1_Slice) Descriptor() ([]byte, []int) {
	return fileDescriptor_0bb23f43f7afb4c1, []int{0, 0}
}

func (m *ManifestV1_Slice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManifestV1_Slice.Unmarshal(m, b)
}
func (m *ManifestV1_Slice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManifestV1_Slice.Marshal(b, m, deterministic)
}
func (m *ManifestV1_Slice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManifestV1_Slice.Merge(m, src)
}
func (m *ManifestV1_Slice) XXX_Size() int {
	return xxx_messageInfo_ManifestV1_Slice.Size(m)
}
func (m *ManifestV1_Slice) XXX_DiscardUnknown() {
	xxx_messageInfo_ManifestV1_Slice.DiscardUnknown(m)
}

var xxx_messageInfo_ManifestV1_Slice proto.InternalMessageInfo

func (m *ManifestV1_Slice) GetChecksum() []byte {
	if m != nil {
		return m.Checksum
	}
	return nil
}

func (m *ManifestV1_Slice) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ManifestV1_Slice) GetLength() uint64 {
	if m != nil {
		return m.Length
	}
	return 0
}

func init() {
	proto.RegisterType((*ManifestV1)(nil), "internal.ManifestV1")
	proto.RegisterType((*ManifestV1_Slice)(nil), "internal.ManifestV1.Slice")
}

func init() { proto.RegisterFile("manifest.proto", fileDescriptor_0bb23f43f7afb4c1) }

var fileDescriptor_0bb23f43f7afb4c1 = []byte{
	// 165 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x4d, 0xcc, 0xcb,
	0x4c, 0x4b, 0x2d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xc8, 0xcc, 0x2b, 0x49,
	0x2d, 0xca, 0x4b, 0xcc, 0x51, 0x5a, 0xc9, 0xc8, 0xc5, 0xe5, 0x0b, 0x95, 0x0c, 0x33, 0x14, 0x12,
	0xe2, 0x62, 0x09, 0xce, 0xac, 0x4a, 0x95, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x09, 0x02, 0xb3, 0x85,
	0x8c, 0xb8, 0xd8, 0x82, 0x73, 0x32, 0x93, 0x53, 0x8b, 0x25, 0x98, 0x14, 0x98, 0x35, 0xb8, 0x8d,
	0xa4, 0xf4, 0x60, 0xba, 0xf5, 0x10, 0x3a, 0xf5, 0xc0, 0x4a, 0x82, 0xa0, 0x2a, 0xa5, 0x82, 0xb9,
	0x58, 0xc1, 0x2c, 0x21, 0x29, 0x2e, 0x0e, 0xe7, 0x8c, 0xd4, 0xe4, 0xec, 0xe2, 0xd2, 0x5c, 0xb0,
	0xa1, 0x3c, 0x41, 0x70, 0xbe, 0x90, 0x18, 0x17, 0x9b, 0x7f, 0x5a, 0x5a, 0x71, 0x6a, 0x89, 0x04,
	0x13, 0xd8, 0x3a, 0x28, 0x0f, 0x24, 0xee, 0x93, 0x9a, 0x97, 0x5e, 0x92, 0x21, 0xc1, 0x0c, 0x11,
	0x87, 0xf0, 0x92, 0xd8, 0xc0, 0x8e, 0x37, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xaa, 0x46, 0x0b,
	0xb6, 0xce, 0x00, 0x00, 0x00,
}
