// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/manifest.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Slice struct {
	Checksum             []byte   `protobuf:"bytes,1,opt,name=Checksum,proto3" json:"Checksum,omitempty"`
	Offset               int64    `protobuf:"varint,2,opt,name=Offset,proto3" json:"Offset,omitempty"`
	Length               int64    `protobuf:"varint,3,opt,name=Length,proto3" json:"Length,omitempty"`
	Kind                 int32    `protobuf:"varint,4,opt,name=Kind,proto3" json:"Kind,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Slice) Reset()         { *m = Slice{} }
func (m *Slice) String() string { return proto.CompactTextString(m) }
func (*Slice) ProtoMessage()    {}
func (*Slice) Descriptor() ([]byte, []int) {
	return fileDescriptor_2539f5857e72bfb4, []int{0}
}

func (m *Slice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Slice.Unmarshal(m, b)
}
func (m *Slice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Slice.Marshal(b, m, deterministic)
}
func (m *Slice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Slice.Merge(m, src)
}
func (m *Slice) XXX_Size() int {
	return xxx_messageInfo_Slice.Size(m)
}
func (m *Slice) XXX_DiscardUnknown() {
	xxx_messageInfo_Slice.DiscardUnknown(m)
}

var xxx_messageInfo_Slice proto.InternalMessageInfo

func (m *Slice) GetChecksum() []byte {
	if m != nil {
		return m.Checksum
	}
	return nil
}

func (m *Slice) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Slice) GetLength() int64 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *Slice) GetKind() int32 {
	if m != nil {
		return m.Kind
	}
	return 0
}

type ManifestV1 struct {
	Version              int64    `protobuf:"varint,5,opt,name=Version,proto3" json:"Version,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=Id,proto3" json:"Id,omitempty"`
	Size                 int64    `protobuf:"varint,1,opt,name=Size,proto3" json:"Size,omitempty"`
	Slices               []*Slice `protobuf:"bytes,2,rep,name=Slices,proto3" json:"Slices,omitempty"`
	ChunkMaxSize         int64    `protobuf:"varint,4,opt,name=ChunkMaxSize,proto3" json:"ChunkMaxSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ManifestV1) Reset()         { *m = ManifestV1{} }
func (m *ManifestV1) String() string { return proto.CompactTextString(m) }
func (*ManifestV1) ProtoMessage()    {}
func (*ManifestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_2539f5857e72bfb4, []int{1}
}

func (m *ManifestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManifestV1.Unmarshal(m, b)
}
func (m *ManifestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManifestV1.Marshal(b, m, deterministic)
}
func (m *ManifestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManifestV1.Merge(m, src)
}
func (m *ManifestV1) XXX_Size() int {
	return xxx_messageInfo_ManifestV1.Size(m)
}
func (m *ManifestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_ManifestV1.DiscardUnknown(m)
}

var xxx_messageInfo_ManifestV1 proto.InternalMessageInfo

func (m *ManifestV1) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ManifestV1) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ManifestV1) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ManifestV1) GetSlices() []*Slice {
	if m != nil {
		return m.Slices
	}
	return nil
}

func (m *ManifestV1) GetChunkMaxSize() int64 {
	if m != nil {
		return m.ChunkMaxSize
	}
	return 0
}

func init() {
	proto.RegisterType((*Slice)(nil), "pb.Slice")
	proto.RegisterType((*ManifestV1)(nil), "pb.ManifestV1")
}

func init() { proto.RegisterFile("pb/manifest.proto", fileDescriptor_2539f5857e72bfb4) }

var fileDescriptor_2539f5857e72bfb4 = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0x49, 0xb2, 0xbb, 0xda, 0xb1, 0x08, 0xce, 0x41, 0x82, 0xa7, 0xb8, 0xa7, 0x9c, 0x56,
	0xd4, 0x47, 0xe8, 0xa9, 0x68, 0x11, 0x52, 0xe8, 0xbd, 0xe9, 0x66, 0xbb, 0xa1, 0x36, 0x1b, 0x9a,
	0x14, 0xc4, 0xb7, 0xf0, 0x8d, 0xa5, 0xd3, 0x55, 0xe8, 0x6d, 0xbe, 0x2f, 0xfc, 0x93, 0x9f, 0x81,
	0xbb, 0x68, 0x9f, 0xf6, 0xeb, 0xe0, 0x3b, 0x97, 0x72, 0x13, 0x0f, 0x43, 0x1e, 0x90, 0x47, 0x5b,
	0x6f, 0xa1, 0x5c, 0x7e, 0xfa, 0x8d, 0xc3, 0x07, 0xb8, 0x9e, 0xf5, 0x6e, 0xb3, 0x4b, 0xc7, 0xbd,
	0x64, 0x8a, 0xe9, 0xa9, 0xf9, 0x67, 0xbc, 0x87, 0xea, 0xa3, 0xeb, 0x92, 0xcb, 0x92, 0x2b, 0xa6,
	0x85, 0x19, 0xe9, 0xe4, 0xdf, 0x5d, 0xd8, 0xe6, 0x5e, 0x8a, 0xb3, 0x3f, 0x13, 0x22, 0x14, 0x6f,
	0x3e, 0xb4, 0xb2, 0x50, 0x4c, 0x97, 0x86, 0xe6, 0xfa, 0x87, 0x01, 0x2c, 0xc6, 0xff, 0x57, 0xcf,
	0x28, 0xe1, 0x6a, 0xe5, 0x0e, 0xc9, 0x0f, 0x41, 0x96, 0x94, 0xfd, 0x43, 0xbc, 0x05, 0x3e, 0x6f,
	0x69, 0xe1, 0xc4, 0xf0, 0x79, 0x7b, 0x5a, 0xb6, 0xf4, 0xdf, 0x8e, 0x4a, 0x09, 0x43, 0x33, 0x3e,
	0x42, 0x45, 0xad, 0x93, 0xe4, 0x4a, 0xe8, 0x9b, 0x97, 0x49, 0x13, 0x6d, 0x43, 0xc6, 0x8c, 0x0f,
	0x58, 0xc3, 0x74, 0xd6, 0x1f, 0xc3, 0x6e, 0xb1, 0xfe, 0xa2, 0x78, 0x41, 0xf1, 0x0b, 0x67, 0x2b,
	0xba, 0xc3, 0xeb, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa2, 0x15, 0x7b, 0x19, 0x1c, 0x01, 0x00,
	0x00,
}
